const LS='appConsuntivi.v01';
const APP_VERSION='v0.6';
const fmtEUR=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const fmtNum=(n,d=1)=>new Intl.NumberFormat('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(n||0));
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const norm=s=>String(s||'').trim();
const monthNames=['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];
const ym=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
const today=new Date();
let state={view:'home',month:ym(today),edit:null,tab:'daily'};
const demo={
  clients:[{id:id(),name:'Solution',type:'daily',dailyRate:550,standardHours:8,active:true},{id:id(),name:'TFB',type:'monthly',dailyRate:0,standardHours:8,active:true}],
  projects:[{id:id(),clientName:'Solution',name:'Equans',active:true},{id:id(),clientName:'TFB',name:'Cliente finale X',active:true}],
  activities:[{id:id(),name:'PM',active:true},{id:id(),name:'AMS',active:true},{id:id(),name:'Gestione',active:true},{id:id(),name:'Meeting',active:true}],
  entries:[{id:id(),date:`${ym(today)}-24`,clientName:'Solution',projectName:'Equans',activityName:'PM',description:'Meeting avanzamento',hours:8,dailyRate:550,type:'daily'}],
  monthly:[{id:id(),month:ym(today),clientName:'TFB',projectName:'Cliente finale X',description:'Supporto mensile',amount:2000,type:'monthly'}],
  billing:{}
};
function id(){return Math.random().toString(36).slice(2,10)}
function load(){try{return JSON.parse(localStorage.getItem(LS))||demo}catch(e){return demo}}
function save(){localStorage.setItem(LS,JSON.stringify(data))}
let data=load();
function monthLabel(m){const [y,mo]=m.split('-').map(Number);return `${monthNames[mo-1]} ${y}`}
function changeMonth(delta){let [y,m]=state.month.split('-').map(Number);m+=delta;if(m<1){m=12;y--}if(m>12){m=1;y++}state.month=`${y}-${String(m).padStart(2,'0')}`;render()}
function dailyAmount(e){return Number(e.dailyRate||0)/8*Number(e.hours||0)}
function dailyDays(e){return Number(e.hours||0)/8}
function rowsForMonth(){return data.entries.filter(e=>e.date?.startsWith(state.month))}
function monthlyRows(){return data.monthly.filter(e=>e.month===state.month)}
function totals(){let h=0,a=0;rowsForMonth().forEach(e=>{h+=Number(e.hours||0);a+=dailyAmount(e)});monthlyRows().forEach(e=>a+=Number(e.amount||0));return {hours:h,days:h/8,amount:a}}
function groupSummary(){const map={}; rowsForMonth().forEach(e=>{const k=`${e.clientName}|${e.projectName||''}|daily`; if(!map[k]) map[k]={client:e.clientName,project:e.projectName,type:'daily',hours:0,amount:0}; map[k].hours+=Number(e.hours||0); map[k].amount+=dailyAmount(e)}); monthlyRows().forEach(e=>{const k=`${e.clientName}|${e.projectName||''}|monthly`; if(!map[k]) map[k]={client:e.clientName,project:e.projectName,type:'monthly',hours:null,amount:0}; map[k].amount+=Number(e.amount||0)}); return Object.values(map).sort((a,b)=>`${a.client}|${a.project||''}`.localeCompare(`${b.client}|${b.project||''}`))}
function billingStatus(r){const key=billKey(r);return data.billing[key]?.status||'Da fatturare'}
function billKey(r){return `${state.month}|${r.client}|${r.project||''}|${r.type}`}
function fiscoText(r){if(r.type==='daily') return `Consulenza - ${monthLabel(state.month)} - Cliente/Progetto: ${r.project||r.client} | Giorni: ${fmtNum((r.hours||0)/8,1)}`; return `Consulenza - ${monthLabel(state.month)} - Cliente/Progetto: ${r.project||r.client}`}
function appShell(content){return `<div class="app"><div class="header"><div class="brand"><img class="brandIcon" src="assets/totime-icon-dark.png" alt="TOTIME"><div><div class="brandName">TOTIME</div><div class="brandTagline">Il tuo tempo. Il tuo valore.</div></div></div><button class="iconbtn" onclick="exportData()" title="Esporta backup">↗</button></div>${content}</div>${nav()}`}
function nav(){const items=[['home','Home'],['timesheet','Timesheet'],['summary','Riepilogo'],['billing','Fatture'],['settings','Config']];return `<div class="nav">${items.map(([v,l])=>`<button class="${state.view===v?'active':''}" onclick="go('${v}')">${l}</button>`).join('')}</div>`}
function monthSelector(){return `<div class="month"><button onclick="changeMonth(-1)">‹</button><strong>${monthLabel(state.month)}</strong><button onclick="changeMonth(1)">›</button></div>`}
function metricLine(hours,amount){return `${fmtNum(hours,1)} h <span class="dot">·</span> ${fmtNum(Number(hours||0)/8,1)} gg/u <span class="dot">·</span> ${fmtEUR(amount)}`}
function monthlyMetricLine(amount){return `Una tantum <span class="dot">·</span> ${fmtEUR(amount)}`}
function go(v){state.view=v;state.edit=null;render()}
function home(){const t=totals();return appShell(`<div class="hello">Ciao Giovanni</div>${monthSelector()}<div class="card total"><div class="sub">Totale mese</div><div class="amount">${fmtEUR(t.amount)}</div><div class="meta"><span>${fmtNum(t.hours,1)} h</span><span>${fmtNum(t.days,1)} gg/u</span></div></div><div class="grid"><button class="primary wide" onclick="newEntryChoice()">+ Nuovo consuntivo</button><button class="menuBtn" onclick="go('timesheet')">🗓 Timesheet <span>›</span></button><button class="menuBtn" onclick="go('summary')">📊 Riepilogo <span>›</span></button><button class="menuBtn" onclick="go('billing')">🧾 Fatturazione <span>›</span></button><button class="menuBtn" onclick="go('settings')">⚙️ Configurazione <span>›</span></button></div>`)}
function newEntryChoice(){state.view='newChoice';render()}
function newChoice(){return appShell(`<h1>Nuovo consuntivo</h1><p class="sub">Cosa vuoi registrare?</p><div class="grid"><button class="menuBtn" onclick="state.view='dailyForm';render()"><span><b>Consuntivo giornaliero</b><br><span class='sub'>Ore su tariffa giornaliera 8h</span></span><span>›</span></button><button class="menuBtn" onclick="state.view='monthlyForm';render()"><span><b>Compenso mensile</b><br><span class='sub'>Una tantum senza ore e giorni</span></span><span>›</span></button></div>`)}
function sediOptions(selected=''){const sedi=['Remoto','Casa','Ufficio','Sede cliente','Onsite cliente','Altro'];return `<option></option>${sedi.map(x=>`<option ${x===selected?'selected':''}>${x}</option>`).join('')}`}
function projectOptions(clientName,selected=''){return `<option></option>${data.projects.filter(p=>p.active&&p.clientName===clientName).map(p=>`<option ${p.name===selected?'selected':''}>${esc(p.name)}</option>`).join('')}`}
function refreshProjectsForForm(form){const client=form.client.value;const project=form.project;project.innerHTML=projectOptions(client,'')}
function dailyForm(){const clients=data.clients.filter(c=>c.type==='daily'&&c.active);const selectedClient=clients[0]?.name||'';return appShell(`<h1>Consuntivo giornaliero</h1><form class="form" onsubmit="saveDaily(event)"><div class="field"><label>Data</label><input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Cliente</label><select name="client" onchange="refreshProjectsForForm(this.form)">${clients.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project">${projectOptions(selectedClient)}</select></div><div class="field"><label>Attività</label><select name="activity"><option></option>${data.activities.filter(a=>a.active).map(a=>`<option>${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Luogo di lavoro / Sede</label><select name="workLocation">${sediOptions()}</select></div><div class="field"><label>Descrizione</label><textarea name="description"></textarea></div><div class="field"><label>Ore consuntivate</label><input name="hours" type="number" step="0.25" value="8"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali"></textarea></div><div class="actions"><button class="primary">Salva</button><button type="button" class="secondary" onclick="go('home')">Annulla</button></div></form>`)}
function dailyEdit(){const e=data.entries.find(x=>x.id===state.edit);if(!e)return timesheet();const clients=data.clients.filter(c=>c.type==='daily'&&c.active);return appShell(`<h1>Modifica consuntivo</h1><form class="form" onsubmit="saveDailyEdit(event)"><div class="field"><label>Data</label><input name="date" type="date" value="${esc(e.date)}"></div><div class="field"><label>Cliente</label><select name="client" onchange="refreshProjectsForForm(this.form)">${clients.map(x=>`<option ${x.name===e.clientName?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project">${projectOptions(e.clientName,e.projectName||'')}</select></div><div class="field"><label>Attività</label><select name="activity"><option></option>${data.activities.filter(a=>a.active).map(a=>`<option ${a.name===e.activityName?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Luogo di lavoro / Sede</label><select name="workLocation">${sediOptions(e.workLocation||'')}</select></div><div class="field"><label>Descrizione</label><textarea name="description">${esc(e.description||'')}</textarea></div><div class="field"><label>Ore consuntivate</label><input name="hours" type="number" step="0.25" value="${Number(e.hours||0)}"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali">${esc(e.notes||'')}</textarea></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary" onclick="duplicateDaily('${e.id}')">Duplica</button><button type="button" class="secondary danger" onclick="deleteDaily('${e.id}')">Elimina</button><button type="button" class="secondary" onclick="go('timesheet')">Annulla</button></div></form>`)}
function monthlyForm(){const clients=data.clients.filter(c=>c.type==='monthly'&&c.active);const selectedClient=clients[0]?.name||'';return appShell(`<h1>Compenso mensile</h1><form class="form" onsubmit="saveMonthly(event)"><div class="field"><label>Mese</label><input name="month" type="month" value="${state.month}"></div><div class="field"><label>Cliente</label><select name="client" onchange="refreshProjectsForForm(this.form)">${clients.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project">${projectOptions(selectedClient)}</select></div><div class="field"><label>Descrizione</label><textarea name="description"></textarea></div><div class="field"><label>Importo</label><input name="amount" type="number" step="0.01" value="2000"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali"></textarea></div><div class="actions"><button class="primary">Salva</button><button type="button" class="secondary" onclick="go('home')">Annulla</button></div></form>`)}
function monthlyEdit(){const e=data.monthly.find(x=>x.id===state.edit);if(!e)return timesheet();const clients=data.clients.filter(c=>c.type==='monthly'&&c.active);return appShell(`<h1>Modifica compenso mensile</h1><form class="form" onsubmit="saveMonthlyEdit(event)"><div class="field"><label>Mese</label><input name="month" type="month" value="${esc(e.month)}"></div><div class="field"><label>Cliente</label><select name="client" onchange="refreshProjectsForForm(this.form)">${clients.map(x=>`<option ${x.name===e.clientName?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project">${projectOptions(e.clientName,e.projectName||'')}</select></div><div class="field"><label>Descrizione</label><textarea name="description">${esc(e.description||'')}</textarea></div><div class="field"><label>Importo</label><input name="amount" type="number" step="0.01" value="${Number(e.amount||0)}"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali">${esc(e.notes||'')}</textarea></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary" onclick="duplicateMonthly('${e.id}')">Duplica</button><button type="button" class="secondary danger" onclick="deleteMonthly('${e.id}')">Elimina</button><button type="button" class="secondary" onclick="go('timesheet')">Annulla</button></div></form>`)}
function saveDaily(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const client=data.clients.find(c=>c.name===f.client);data.entries.push({id:id(),date:f.date,clientName:f.client,projectName:f.project,activityName:f.activity,workLocation:f.workLocation||'',description:f.description,notes:f.notes||'',hours:Number(f.hours||0),dailyRate:Number(client?.dailyRate||0),type:'daily'});save();state.month=f.date.slice(0,7);go('timesheet')}
function saveDailyEdit(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const e=data.entries.find(x=>x.id===state.edit);if(!e)return;const client=data.clients.find(c=>c.name===f.client);Object.assign(e,{date:f.date,clientName:f.client,projectName:f.project,activityName:f.activity,workLocation:f.workLocation||'',description:f.description,notes:f.notes||'',hours:Number(f.hours||0),dailyRate:Number(client?.dailyRate||e.dailyRate||0)});save();state.month=f.date.slice(0,7);state.edit=null;go('timesheet')}
function saveMonthly(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));data.monthly.push({id:id(),month:f.month,clientName:f.client,projectName:f.project,description:f.description,notes:f.notes||'',amount:Number(f.amount||0),type:'monthly'});save();state.month=f.month;go('timesheet')}
function saveMonthlyEdit(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const e=data.monthly.find(x=>x.id===state.edit);if(!e)return;Object.assign(e,{month:f.month,clientName:f.client,projectName:f.project,description:f.description,notes:f.notes||'',amount:Number(f.amount||0)});save();state.month=f.month;state.edit=null;go('timesheet')}
function editDaily(idv){state.edit=idv;state.view='dailyEdit';render()}
function editMonthly(idv){state.edit=idv;state.view='monthlyEdit';render()}
function duplicateDaily(idv){const e=data.entries.find(x=>x.id===idv);if(!e)return;data.entries.push({...e,id:id()});save();state.month=e.date.slice(0,7);state.edit=null;go('timesheet')}
function duplicateMonthly(idv){const e=data.monthly.find(x=>x.id===idv);if(!e)return;data.monthly.push({...e,id:id()});save();state.month=e.month;state.edit=null;go('timesheet')}
function deleteDaily(idv){const e=data.entries.find(x=>x.id===idv);if(!e)return;if(!confirm('Eliminare questo consuntivo giornaliero?'))return;data.entries=data.entries.filter(x=>x.id!==idv);save();state.edit=null;go('timesheet')}
function deleteMonthly(idv){const e=data.monthly.find(x=>x.id===idv);if(!e)return;if(!confirm('Eliminare questo compenso mensile?'))return;data.monthly=data.monthly.filter(x=>x.id!==idv);save();state.edit=null;go('timesheet')}
function timesheet(){const rows=[...rowsForMonth().map(e=>({...e,sort:e.date})),...monthlyRows().map(e=>({...e,date:e.month+'-01',sort:e.month+'-01'}))].sort((a,b)=>b.sort.localeCompare(a.sort));const t=totals();return appShell(`<h1>Timesheet</h1>${monthSelector()}<div class="small">Totale mese: ${fmtNum(t.hours,1)}h | ${fmtNum(t.days,1)} gg</div><button class="primary" style="margin-top:14px" onclick="newEntryChoice()">+ Nuovo consuntivo</button><div class="list">${rows.length?rows.map(r=>r.type==='monthly'?monthlyLine(r):dailyLine(r)).join(''):'<div class="empty">Nessun consuntivo nel mese.</div>'}</div>`)}
function dailyLine(e){const parts=[e.activityName,e.workLocation,e.description].filter(Boolean);return `<div class="row" onclick="editDaily('${e.id}')"><div class="date">${e.date.slice(8,10)}/${e.date.slice(5,7)}</div><div><div class="title">${esc(e.clientName)} ${e.projectName?'/ '+esc(e.projectName):''}</div><div class="desc">${esc(parts.join(' · '))}${e.notes?' · 📝':''}</div></div><div class="value">${fmtNum(e.hours,1)}h<br><span class="sub">›</span></div></div>`}
function monthlyLine(e){return `<div class="row" onclick="editMonthly('${e.id}')"><div class="date">${e.date.slice(8,10)}/${e.date.slice(5,7)}</div><div><div class="title">${esc(e.clientName)} ${e.projectName?'/ '+esc(e.projectName):''}</div><div class="desc">Una tantum mensile · ${esc(e.description||'')}${e.notes?' · 📝':''}</div></div><div class="value"><span class="sub">›</span></div></div>`}
function summary(){const rows=groupSummary();const t=totals();return appShell(`<h1>Riepilogo</h1>${monthSelector()}<div class="card"><b>Totale mese</b><div class="metricLine">${metricLine(t.hours,t.amount)}</div></div><div class="list">${rows.map(r=>`<div class="row summaryRow"><div></div><div><div class="title">${esc(r.client)}</div><div class="desc">${esc(r.project||'Senza progetto')}</div><div class="metricLine">${r.type==='daily'?metricLine(r.hours,r.amount):monthlyMetricLine(r.amount)}</div></div><div></div></div>`).join('')||'<div class="empty">Nessun dato.</div>'}</div>`)}
function billing(){const rows=groupSummary();return appShell(`<h1>Fatturazione</h1>${monthSelector()}<div class="list">${rows.map((r,i)=>{const st=billingStatus(r);const cls=st==='Incassato'?'green':st==='Da fatturare'?'orange':st==='Fattura emessa'?'blue':'gray';return `<div class="row" onclick="billingDetail(${i})"><div></div><div><div class="title">${esc(r.client)} ${r.project?'/ '+esc(r.project):''}</div><div class="metricLine">${r.type==='daily'?metricLine(r.hours,r.amount):monthlyMetricLine(r.amount)}</div><span class="tag ${cls}">${st}</span></div><div class="value">›</div></div>`}).join('')||'<div class="empty">Nessuna riga fatturabile.</div>'}</div>`)}
function billingDetail(i){state.billIndex=i;state.view='billingDetail';render()}
function billingDetailView(){const r=groupSummary()[state.billIndex];const key=billKey(r);const b=data.billing[key]||{status:'Da fatturare'};const txt=fiscoText(r);return appShell(`<h1>${r.client} ${r.project?'/ '+r.project:''}</h1><div class="card"><div class="sub">Periodo</div><b>${monthLabel(state.month)}</b><br><br><div class="sub">Valori</div><div class="metricLine">${r.type==='daily'?metricLine(r.hours,r.amount):monthlyMetricLine(r.amount)}</div><br><div class="sub">Stato</div><b>${b.status}</b></div><div class="card"><div class="sub">Descrizione Fiscozen</div><div class="copybox" id="copyText">${txt}</div><div class="actions"><button class="primary" onclick="copyFisco()">Copia descrizione</button><button class="secondary" onclick="setStatus('${key}','Fattura emessa')">Segna come fattura emessa</button><button class="secondary" onclick="setStatus('${key}','Incassato')">Segna come incassato</button><button class="secondary danger" onclick="setStatus('${key}','Escluso')">Escludi</button></div></div>`)}
function copyFisco(){navigator.clipboard?.writeText(document.getElementById('copyText').innerText);alert('Descrizione copiata')}
function setStatus(key,status){data.billing[key]={...(data.billing[key]||{}),status};save();go('billing')}

function settings(){return appShell(`<h1>Configurazione</h1><div class="list"><div class="row" onclick="state.view='clients';render()"><div>👤</div><div class="title">Clienti</div><div>›</div></div><div class="row" onclick="state.view='projects';render()"><div>📁</div><div class="title">Progetti / Clienti finali</div><div>›</div></div><div class="row" onclick="state.view='activities';render()"><div>🏷</div><div class="title">Attività</div><div>›</div></div><div class="row"><div>🎨</div><div><div class="title">Branding / Logo</div><div class="desc">TOTIME predefinito incluso</div></div><div></div></div></div><div class="card"><b>Backup / Import</b><p class="sub">Salva o carica i dati della web app. Utile prima di importare i consuntivi da Excel/CSV.</p><div class="actions"><button class="secondary" onclick="exportData()">Esporta backup JSON</button><label class="secondary" style="display:flex;cursor:pointer">Importa backup JSON<input type="file" accept="application/json" style="display:none" onchange="importBackup(event)"></label><label class="secondary" style="display:flex;cursor:pointer">Importa consuntivi CSV<input type="file" accept=".csv,text/csv" style="display:none" onchange="importCsv(event)"></label></div><p class="sub">CSV atteso: Data;Cliente;Cliente/Progetto;Attività;Descrizione;Ore;Tipo;Importo;Mese;Luogo/Sede;Note</p></div><button class="secondary" onclick="resetDemo()">Ripristina dati demo</button>`)}

function clients(){return appShell(`<h1>Clienti</h1><form class="form" onsubmit="addClient(event)"><div class="field"><label>Nome cliente</label><input name="name" required></div><div class="field"><label>Tipo compenso</label><select name="type"><option value="daily">Tariffa giornaliera 8h</option><option value="monthly">Una tantum mensile</option></select></div><div class="field"><label>Tariffa giornaliera</label><input name="rate" type="number" step="0.01" value="550"></div><button class="primary">Aggiungi cliente</button></form><div class="list">${data.clients.map(c=>`<div class="row" onclick="editClient('${c.id}')"><div></div><div><div class="title">${esc(c.name)}</div><div class="desc">${c.type==='daily'?`Tariffa giornaliera 8h · ${fmtEUR(c.dailyRate)}`:'Una tantum mensile'} · ${c.active?'Attivo':'Disattivo'}</div></div><div>›</div></div>`).join('')||'<div class="empty">Nessun cliente.</div>'}</div>`)}
function editClient(id){state.edit=id;state.view='clientEdit';render()}
function clientEdit(){const c=data.clients.find(x=>x.id===state.edit); if(!c) return clients(); return appShell(`<h1>Modifica cliente</h1><form class="form" onsubmit="saveClient(event)"><div class="field"><label>Nome cliente</label><input name="name" value="${esc(c.name)}" required></div><div class="field"><label>Tipo compenso</label><select name="type"><option value="daily" ${c.type==='daily'?'selected':''}>Tariffa giornaliera 8h</option><option value="monthly" ${c.type==='monthly'?'selected':''}>Una tantum mensile</option></select></div><div class="field"><label>Tariffa giornaliera</label><input name="rate" type="number" step="0.01" value="${Number(c.dailyRate||0)}"></div><div class="field"><label>Attivo</label><select name="active"><option value="true" ${c.active?'selected':''}>Sì</option><option value="false" ${!c.active?'selected':''}>No</option></select></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary danger" onclick="deleteClient('${c.id}')">Elimina cliente</button><button type="button" class="secondary" onclick="state.view='clients';render()">Annulla</button></div></form>`)}
function addClient(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const name=norm(f.name); if(!name) return; if(data.clients.some(c=>c.name.toLowerCase()===name.toLowerCase())) return alert('Cliente già presente.');data.clients.push({id:id(),name,type:f.type,dailyRate:Number(f.rate||0),standardHours:8,active:true});save();render()}
function saveClient(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const c=data.clients.find(x=>x.id===state.edit); if(!c) return; const old=c.name; const name=norm(f.name); if(!name) return; c.name=name; c.type=f.type; c.dailyRate=Number(f.rate||0); c.standardHours=8; c.active=f.active==='true'; if(old!==name){data.projects.forEach(p=>{if(p.clientName===old)p.clientName=name});data.entries.forEach(e=>{if(e.clientName===old)e.clientName=name});data.monthly.forEach(m=>{if(m.clientName===old)m.clientName=name});data.billing=remapBillingClient(data.billing,old,name)} save();state.view='clients';state.edit=null;render()}
function remapBillingClient(billing,oldName,newName){const out={};Object.entries(billing||{}).forEach(([k,v])=>{out[k.replace(`|${oldName}|`,`|${newName}|`)]=v});return out}
function deleteClient(idv){const c=data.clients.find(x=>x.id===idv); if(!c) return; if(!confirm(`Eliminare il cliente "${c.name}" dalla configurazione? I consuntivi storici già inseriti resteranno salvati.`)) return; data.clients=data.clients.filter(x=>x.id!==idv); save(); state.view='clients'; state.edit=null; render()}

function projects(){return appShell(`<h1>Progetti / Clienti finali</h1><form class="form" onsubmit="addProject(event)"><div class="field"><label>Cliente collegato</label><select name="client">${data.clients.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Nome progetto / cliente finale</label><input name="name" required></div><button class="primary">Aggiungi progetto</button></form><div class="list">${data.projects.map(p=>`<div class="row" onclick="editProject('${p.id}')"><div></div><div><div class="title">${esc(p.clientName)}</div><div class="desc">${esc(p.name)} · ${p.active?'Attivo':'Disattivo'}</div></div><div>›</div></div>`).join('')||'<div class="empty">Nessun progetto.</div>'}</div>`)}
function editProject(id){state.edit=id;state.view='projectEdit';render()}
function projectEdit(){const p=data.projects.find(x=>x.id===state.edit); if(!p) return projects(); return appShell(`<h1>Modifica progetto</h1><form class="form" onsubmit="saveProject(event)"><div class="field"><label>Cliente collegato</label><select name="client">${data.clients.map(c=>`<option ${c.name===p.clientName?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Nome progetto / cliente finale</label><input name="name" value="${esc(p.name)}" required></div><div class="field"><label>Attivo</label><select name="active"><option value="true" ${p.active?'selected':''}>Sì</option><option value="false" ${!p.active?'selected':''}>No</option></select></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary danger" onclick="deleteProject('${p.id}')">Elimina progetto</button><button type="button" class="secondary" onclick="state.view='projects';render()">Annulla</button></div></form>`)}
function addProject(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const name=norm(f.name); if(!name) return; data.projects.push({id:id(),clientName:f.client,name,active:true});save();render()}
function saveProject(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const p=data.projects.find(x=>x.id===state.edit); if(!p) return; const old=p.name; const name=norm(f.name); p.clientName=f.client; p.name=name; p.active=f.active==='true'; if(old!==name){data.entries.forEach(e=>{if(e.projectName===old)e.projectName=name});data.monthly.forEach(m=>{if(m.projectName===old)m.projectName=name});data.billing=remapBillingProject(data.billing,old,name)} save();state.view='projects';state.edit=null;render()}
function remapBillingProject(billing,oldName,newName){const out={};Object.entries(billing||{}).forEach(([k,v])=>{const parts=k.split('|'); if(parts[2]===oldName) parts[2]=newName; out[parts.join('|')]=v});return out}
function deleteProject(idv){const p=data.projects.find(x=>x.id===idv); if(!p) return; if(!confirm(`Eliminare il progetto "${p.name}" dalla configurazione? I consuntivi storici già inseriti resteranno salvati.`)) return; data.projects=data.projects.filter(x=>x.id!==idv); save();state.view='projects';state.edit=null;render()}

function activities(){return appShell(`<h1>Attività</h1><form class="form" onsubmit="addActivity(event)"><div class="field"><label>Nome attività</label><input name="name" required></div><button class="primary">Aggiungi attività</button></form><div class="list">${data.activities.map(a=>`<div class="row" onclick="editActivity('${a.id}')"><div></div><div><div class="title">${esc(a.name)}</div><div class="desc">${a.active?'Attiva':'Disattiva'}</div></div><div>›</div></div>`).join('')||'<div class="empty">Nessuna attività.</div>'}</div>`)}
function editActivity(id){state.edit=id;state.view='activityEdit';render()}
function activityEdit(){const a=data.activities.find(x=>x.id===state.edit); if(!a) return activities(); return appShell(`<h1>Modifica attività</h1><form class="form" onsubmit="saveActivity(event)"><div class="field"><label>Nome attività</label><input name="name" value="${esc(a.name)}" required></div><div class="field"><label>Attiva</label><select name="active"><option value="true" ${a.active?'selected':''}>Sì</option><option value="false" ${!a.active?'selected':''}>No</option></select></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary danger" onclick="deleteActivity('${a.id}')">Elimina attività</button><button type="button" class="secondary" onclick="state.view='activities';render()">Annulla</button></div></form>`)}
function addActivity(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const name=norm(f.name); if(!name) return; data.activities.push({id:id(),name,active:true});save();render()}
function saveActivity(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const a=data.activities.find(x=>x.id===state.edit); if(!a) return; const old=a.name; const name=norm(f.name); a.name=name; a.active=f.active==='true'; if(old!==name){data.entries.forEach(e=>{if(e.activityName===old)e.activityName=name})} save();state.view='activities';state.edit=null;render()}
function deleteActivity(idv){const a=data.activities.find(x=>x.id===idv); if(!a) return; if(!confirm(`Eliminare l'attività "${a.name}" dalla configurazione? I consuntivi storici già inseriti resteranno salvati.`)) return; data.activities=data.activities.filter(x=>x.id!==idv); save();state.view='activities';state.edit=null;render()}

function importBackup(ev){const file=ev.target.files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{try{const incoming=JSON.parse(reader.result); if(!incoming.clients||!incoming.entries) throw new Error('Formato non valido'); data=incoming; save(); alert('Backup importato correttamente.'); go('home')}catch(e){alert('File JSON non valido.')}}; reader.readAsText(file)}
function parseCsvLine(line,sep){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out.map(x=>x.trim())}
function canonHeader(h){return String(h||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\w/ ]+/g,'').replace(/\s+/g,' ')}
function importCsv(ev){const file=ev.target.files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{try{const text=reader.result.replace(/^\uFEFF/,'').trim(); if(!text) return alert('CSV vuoto.'); const lines=text.split(/\r?\n/).filter(Boolean); const sep=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?';':','; const headers=parseCsvLine(lines.shift(),sep).map(canonHeader); const get=(row,names)=>{for(const n of names.map(canonHeader)){const i=headers.indexOf(n); if(i>=0) return row[i]||''} return ''}; let count=0; lines.forEach(line=>{const row=parseCsvLine(line,sep); if(!row.some(x=>norm(x))) return; const tipoRaw=get(row,['tipo','type']); const tipo=(tipoRaw||'Tariffa giornaliera 8h').toLowerCase(); const cliente=norm(get(row,['cliente','client'])); if(!cliente) return; const isMonthly=tipo.includes('mens')||tipo.includes('monthly')||tipo.includes('una tantum'); ensureClient(cliente,isMonthly?'monthly':'daily'); const progetto=norm(get(row,['cliente/progetto','progetto','cliente finale','project'])); if(progetto) ensureProject(cliente,progetto); const att=norm(get(row,['attività','attivita','attivit','activity'])); if(att) ensureActivity(att); const descrizione=get(row,['descrizione','description']); const luogo=norm(get(row,['luogo/sede','luogo','sede','luogo di lavoro','work location','location'])); const note=get(row,['note','notes']); if(isMonthly){const mese=norm(get(row,['mese','month'])) || toMonth(get(row,['data','date'])); const amount=parseAmount(get(row,['importo','amount'])); data.monthly.push({id:id(),month:mese||state.month,clientName:cliente,projectName:progetto,description:descrizione,notes:note,amount,type:'monthly'}); count++}else{const date=toDate(get(row,['data','date'])); const hours=parseAmount(get(row,['ore','hours'])); const amount=parseAmount(get(row,['importo','amount'])); const client=data.clients.find(c=>c.name===cliente); let rowDailyRate=Number(client?.dailyRate||0); if(amount>0 && hours>0) rowDailyRate=amount/hours*8; if((!client.dailyRate || Number(client.dailyRate)===0) && rowDailyRate>0) client.dailyRate=rowDailyRate; data.entries.push({id:id(),date:date||new Date().toISOString().slice(0,10),clientName:cliente,projectName:progetto,activityName:att,workLocation:luogo,description:descrizione,notes:note,hours,dailyRate:rowDailyRate,type:'daily'}); count++}}); save(); alert(`Import completato: ${count} righe.`); go('timesheet')}catch(e){console.error(e);alert('Errore durante import CSV. Verifica formato colonne.')}}; reader.readAsText(file,'windows-1252')}
function ensureClient(name,type){if(!data.clients.some(c=>c.name.toLowerCase()===name.toLowerCase())) data.clients.push({id:id(),name,type:type||'daily',dailyRate:0,standardHours:8,active:true})}
function ensureProject(clientName,name){if(!data.projects.some(p=>p.clientName===clientName&&p.name.toLowerCase()===name.toLowerCase())) data.projects.push({id:id(),clientName,name,active:true})}
function ensureActivity(name){if(!data.activities.some(a=>a.name.toLowerCase()===name.toLowerCase())) data.activities.push({id:id(),name,active:true})}
function parseAmount(v){return Number(String(v||'0').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
function toDate(v){v=norm(v); if(!v) return ''; if(/^\d{4}-\d{2}-\d{2}$/.test(v)) return v; const m=v.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/); if(m) return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`; return ''}
function toMonth(v){const d=toDate(v); if(d) return d.slice(0,7); v=norm(v); if(/^\d{4}-\d{2}$/.test(v)) return v; return ''}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='totime-backup.json';a.click()}
function resetDemo(){if(confirm('Ripristinare i dati demo?')){data=JSON.parse(JSON.stringify(demo));save();go('home')}}
function render(){let html=''; if(state.view==='home')html=home(); if(state.view==='newChoice')html=newChoice(); if(state.view==='dailyForm')html=dailyForm(); if(state.view==='dailyEdit')html=dailyEdit(); if(state.view==='monthlyForm')html=monthlyForm(); if(state.view==='monthlyEdit')html=monthlyEdit(); if(state.view==='timesheet')html=timesheet(); if(state.view==='summary')html=summary(); if(state.view==='billing')html=billing(); if(state.view==='billingDetail')html=billingDetailView(); if(state.view==='settings')html=settings(); if(state.view==='clients')html=clients(); if(state.view==='projects')html=projects(); if(state.view==='activities')html=activities(); if(state.view==='clientEdit')html=clientEdit(); if(state.view==='projectEdit')html=projectEdit(); if(state.view==='activityEdit')html=activityEdit(); document.getElementById('app').innerHTML=html}
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
render();
